### ISSUE TITLE
Socket error in imap-client.py

### ISSUE THREAD

**Issue by ghallford** [prbinu/dmarc-report-processor#3]
Hi, I am getting the below error on a new install of this:

``
perl bin/imap-client.py -s <removed server name> -p 993 -u dmarc -f inbox -c /etc/pki/tls/certs/ca-

bundle.crt -o /tmp
Password:
Traceback (most recent call last):
  File "bin/imap-client.py", line 158, in <module>
    main()
  File "bin/imap-client.py", line 139, in main
    mail.login(args.user, args.pwd)
  File "/usr/lib64/python2.7/imaplib.py", line 517, in login
    typ, dat = self._simple_command('LOGIN', user, self._quote(password))
  File "/usr/lib64/python2.7/imaplib.py", line 1082, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib64/python2.7/imaplib.py", line 911, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.abort: command: LOGIN => socket error: EOF
``

**Comment by ghallford** [comment]
Problem was on the imap server side. Thanks.
